---
- name: Cleanup AS3 configuration
  hosts: all
  gather_facts: false
  connection: local
  environment:
    no_proxy: localhost,example.com

  tasks:
    - name: Execute AS3 Cleanup role against each defined application
      ansible.builtin.include_role:
        name: as3_deployment_role
        tasks_from: remove_as3.yml

    - name: Set results status to success
      ansible.builtin.set_stats:
        data:
          RESULT_STATUS: "SUCCESS"
      delegate_to: localhost
      run_once: true